# Generated by Django 3.0.7 on 2020-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(upload_to='')),
                ('style_image', models.FileField(upload_to='')),
            ],
        ),
    ]
